sudo: required
language: php
php:
  - 7.3.2
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com


before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - nvm install 7.7.1
  - npm install npm@latest -g
  - npm install -g jshint
  - npm install
script:
  - vendor/bin/phpunit --coverage-text
  - npm run production
 # build docker images
  - docker build -t ccss/micro-service .
  - docker run --rm -it -d -p 8080:8080 ccss/micro-service
  - docker tag ccss/micro-service registry.heroku.com/$HEROKU_APP_NAME/web
deploy:
  provider: script
  script:
  # push to dockerhub
    docker push ccss/micro-service;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master